# Generated by Django 5.2.15 on 2026-07-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('pays', models.CharField(default='+225', max_length=10, verbose_name='Indicatif Pays')),
                ('telephone', models.CharField(max_length=50, verbose_name='Numéro de téléphone')),
                ('type_inscription', models.CharField(choices=[('programme', 'Programme Alignement Sacré (6 semaines)'), ('atelier', "Atelier d'Éveil Intérieur (mensuel)")], max_length=20, verbose_name="Type d'inscription")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_creation'],
            },
        ),
    ]
