# Generated by Django 5.2.15 on 2026-07-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='type_inscription',
        ),
        migrations.AddField(
            model_name='inscription',
            name='capture_paiement',
            field=models.FileField(default='', upload_to='captures_paiement/', verbose_name='Capture de paiement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscription',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
    ]
