# Generated by Django 5.2.15 on 2026-07-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0002_remove_inscription_pays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='moyen_paiement',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Moyen de paiement'),
        ),
    ]
