# Generated by Django 5.2.15 on 2026-07-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0003_inscription_moyen_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pré-inscription (Temp)',
                'verbose_name_plural': 'Pré-inscriptions (Temp)',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='inscription',
            name='certificat_envoye',
            field=models.BooleanField(default=False, verbose_name='Certificat envoyé'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Transaction (GeniusPay)'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='capture_paiement',
            field=models.FileField(blank=True, null=True, upload_to='captures_paiement/', verbose_name='Capture de paiement'),
        ),
    ]
