# Generated by Django 5.2.15 on 2026-07-27 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0004_preinscription_inscription_certificat_envoye_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreInscription',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='moyen_paiement',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='transaction_id',
        ),
    ]
