# Generated by Django 5.2.15 on 2026-07-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0005_delete_preinscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='date_envoi_certificat',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi du certificat"),
        ),
    ]
