# Generated by Django 5.2.15 on 2026-07-31 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0006_inscription_date_envoi_certificat'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='fichier_certificat',
            field=models.FileField(blank=True, null=True, upload_to='certificats/', verbose_name='Fichier du certificat PDF'),
        ),
    ]
