# Generated by Django 5.2.15 on 2026-07-31 01:24

import programme.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0007_inscription_fichier_certificat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='capture_paiement',
            field=models.FileField(blank=True, null=True, upload_to=programme.models.capture_upload_path, verbose_name='Capture de paiement'),
        ),
    ]
